#include "FormatWindowsError.hpp"

#include <d3dumddi.h>

namespace gs {

// From https://learn.microsoft.com/en-us/windows/win32/seccrypto/retrieving-error-messages
WDynString FormatWindowsError(const unsigned long dwErr) noexcept
{
    WCHAR wszMsgBuff[512];  // Buffer for text.

    // Try to get the message from the system errors.
    DWORD dwChars = FormatMessageW(FORMAT_MESSAGE_FROM_SYSTEM |
        FORMAT_MESSAGE_IGNORE_INSERTS,
        NULL,
        dwErr,
        0,
        wszMsgBuff,
        512,
        NULL);

    if(0 == dwChars)
    {
        // The error code did not exist in the system errors.
        // Try Ntdsbmsg.dll for the error code.

        // Load the library.
        HINSTANCE hInst = LoadLibraryW(L"Ntdsbmsg.dll");
        if(NULL == hInst)
        {
            return L"Could load Ntdsbmsg.dll";
        }

        // Try getting message text from ntdsbmsg.
        dwChars = FormatMessageW(FORMAT_MESSAGE_FROM_HMODULE |
            FORMAT_MESSAGE_IGNORE_INSERTS,
            hInst,
            dwErr,
            0,
            wszMsgBuff,
            512,
            NULL);

        // Free the library.
        FreeLibrary(hInst);
    }

    return WDynString(static_cast<WCHAR*>(wszMsgBuff));
}


C8ConstExprString StringifyFacility(const long facility) noexcept
{
    switch(facility)
    {
        case FACILITY_NULL: return u8"FACILITY_NULL";
        case FACILITY_RPC: return u8"FACILITY_RPC";
        case FACILITY_DISPATCH: return u8"FACILITY_DISPATCH";
        case FACILITY_STORAGE: return u8"FACILITY_STORAGE";
        case FACILITY_ITF: return u8"FACILITY_ITF";
        case FACILITY_WIN32: return u8"FACILITY_WIN32";
        case FACILITY_WINDOWS: return u8"FACILITY_WINDOWS";
        // case FACILITY_SSPI: return u8"FACILITY_SSPI";
        case FACILITY_SECURITY: return u8"FACILITY_SECURITY";
        case FACILITY_CONTROL: return u8"FACILITY_CONTROL";
        case FACILITY_CERT: return u8"FACILITY_CERT";
        case FACILITY_INTERNET: return u8"FACILITY_INTERNET";
        case FACILITY_MEDIASERVER: return u8"FACILITY_MEDIASERVER";
        case FACILITY_MSMQ: return u8"FACILITY_MSMQ";
        case FACILITY_SETUPAPI: return u8"FACILITY_SETUPAPI";
        case FACILITY_SCARD: return u8"FACILITY_SCARD";
        case FACILITY_COMPLUS: return u8"FACILITY_COMPLUS";
        case FACILITY_AAF: return u8"FACILITY_AAF";
        case FACILITY_URT: return u8"FACILITY_URT";
        case FACILITY_ACS: return u8"FACILITY_ACS";
        case FACILITY_DPLAY: return u8"FACILITY_DPLAY";
        case FACILITY_UMI: return u8"FACILITY_UMI";
        case FACILITY_SXS: return u8"FACILITY_SXS";
        case FACILITY_WINDOWS_CE: return u8"FACILITY_WINDOWS_CE";
        case FACILITY_HTTP: return u8"FACILITY_HTTP";
        case FACILITY_USERMODE_COMMONLOG: return u8"FACILITY_USERMODE_COMMONLOG";
        case FACILITY_WER: return u8"FACILITY_WER";
        case FACILITY_USERMODE_FILTER_MANAGER: return u8"FACILITY_USERMODE_FILTER_MANAGER";
        case FACILITY_BACKGROUNDCOPY: return u8"FACILITY_BACKGROUNDCOPY";
        case FACILITY_CONFIGURATION: return u8"FACILITY_CONFIGURATION";
        // case FACILITY_WIA: return u8"FACILITY_WIA";
        case FACILITY_STATE_MANAGEMENT: return u8"FACILITY_STATE_MANAGEMENT";
        case FACILITY_METADIRECTORY: return u8"FACILITY_METADIRECTORY";
        case FACILITY_WINDOWSUPDATE: return u8"FACILITY_WINDOWSUPDATE";
        case FACILITY_DIRECTORYSERVICE: return u8"FACILITY_DIRECTORYSERVICE";
        case FACILITY_GRAPHICS: return u8"FACILITY_GRAPHICS";
        case FACILITY_SHELL: return u8"FACILITY_SHELL";
        // case FACILITY_NAP: return u8"FACILITY_NAP";
        case FACILITY_TPM_SERVICES: return u8"FACILITY_TPM_SERVICES";
        case FACILITY_TPM_SOFTWARE: return u8"FACILITY_TPM_SOFTWARE";
        case FACILITY_UI: return u8"FACILITY_UI";
        case FACILITY_XAML: return u8"FACILITY_XAML";
        case FACILITY_ACTION_QUEUE: return u8"FACILITY_ACTION_QUEUE";
        // case FACILITY_PLA: return u8"FACILITY_PLA";
        case FACILITY_WINDOWS_SETUP: return u8"FACILITY_WINDOWS_SETUP";
        case FACILITY_FVE: return u8"FACILITY_FVE";
        case FACILITY_FWP: return u8"FACILITY_FWP";
        case FACILITY_WINRM: return u8"FACILITY_WINRM";
        case FACILITY_NDIS: return u8"FACILITY_NDIS";
        case FACILITY_USERMODE_HYPERVISOR: return u8"FACILITY_USERMODE_HYPERVISOR";
        case FACILITY_CMI: return u8"FACILITY_CMI";
        case FACILITY_USERMODE_VIRTUALIZATION: return u8"FACILITY_USERMODE_VIRTUALIZATION";
        case FACILITY_USERMODE_VOLMGR: return u8"FACILITY_USERMODE_VOLMGR";
        case FACILITY_BCD: return u8"FACILITY_BCD";
        case FACILITY_USERMODE_VHD: return u8"FACILITY_USERMODE_VHD";
        case FACILITY_USERMODE_HNS: return u8"FACILITY_USERMODE_HNS";
        case FACILITY_SDIAG: return u8"FACILITY_SDIAG";
        // case FACILITY_WEBSERVICES: return u8"FACILITY_WEBSERVICES";
        case FACILITY_WINPE: return u8"FACILITY_WINPE";
        case FACILITY_WPN: return u8"FACILITY_WPN";
        case FACILITY_WINDOWS_STORE: return u8"FACILITY_WINDOWS_STORE";
        case FACILITY_INPUT: return u8"FACILITY_INPUT";
        case FACILITY_QUIC: return u8"FACILITY_QUIC";
        case FACILITY_EAP: return u8"FACILITY_EAP";
        case FACILITY_IORING: return u8"FACILITY_IORING";
        case FACILITY_WINDOWS_DEFENDER: return u8"FACILITY_WINDOWS_DEFENDER";
        case FACILITY_OPC: return u8"FACILITY_OPC";
        case FACILITY_XPS: return u8"FACILITY_XPS";
        // case FACILITY_MBN: return u8"FACILITY_MBN";
        case FACILITY_POWERSHELL: return u8"FACILITY_POWERSHELL";
        case FACILITY_RAS: return u8"FACILITY_RAS";
        case FACILITY_P2P_INT: return u8"FACILITY_P2P_INT";
        case FACILITY_P2P: return u8"FACILITY_P2P";
        case FACILITY_DAF: return u8"FACILITY_DAF";
        case FACILITY_BLUETOOTH_ATT: return u8"FACILITY_BLUETOOTH_ATT";
        case FACILITY_AUDIO: return u8"FACILITY_AUDIO";
        case FACILITY_STATEREPOSITORY: return u8"FACILITY_STATEREPOSITORY";
        case FACILITY_VISUALCPP: return u8"FACILITY_VISUALCPP";
        case FACILITY_SCRIPT: return u8"FACILITY_SCRIPT";
        case FACILITY_PARSE: return u8"FACILITY_PARSE";
        case FACILITY_BLB: return u8"FACILITY_BLB";
        case FACILITY_BLB_CLI: return u8"FACILITY_BLB_CLI";
        case FACILITY_WSBAPP: return u8"FACILITY_WSBAPP";
        case FACILITY_BLBUI: return u8"FACILITY_BLBUI";
        case FACILITY_USN: return u8"FACILITY_USN";
        case FACILITY_USERMODE_VOLSNAP: return u8"FACILITY_USERMODE_VOLSNAP";
        case FACILITY_TIERING: return u8"FACILITY_TIERING";
        case FACILITY_WSB_ONLINE: return u8"FACILITY_WSB_ONLINE";
        case FACILITY_ONLINE_ID: return u8"FACILITY_ONLINE_ID";
        case FACILITY_DEVICE_UPDATE_AGENT: return u8"FACILITY_DEVICE_UPDATE_AGENT";
        case FACILITY_DRVSERVICING: return u8"FACILITY_DRVSERVICING";
        case FACILITY_DLS: return u8"FACILITY_DLS";
        case FACILITY_DELIVERY_OPTIMIZATION: return u8"FACILITY_DELIVERY_OPTIMIZATION";
        case FACILITY_USERMODE_SPACES: return u8"FACILITY_USERMODE_SPACES";
        case FACILITY_USER_MODE_SECURITY_CORE: return u8"FACILITY_USER_MODE_SECURITY_CORE";
        case FACILITY_USERMODE_LICENSING: return u8"FACILITY_USERMODE_LICENSING";
        case FACILITY_SOS: return u8"FACILITY_SOS";
        case FACILITY_OCP_UPDATE_AGENT: return u8"FACILITY_OCP_UPDATE_AGENT";
        case FACILITY_DEBUGGERS: return u8"FACILITY_DEBUGGERS";
        case FACILITY_SPP: return u8"FACILITY_SPP";
        // case FACILITY_RESTORE: return u8"FACILITY_RESTORE";
        // case FACILITY_DMSERVER: return u8"FACILITY_DMSERVER";
        case FACILITY_DEPLOYMENT_SERVICES_SERVER: return u8"FACILITY_DEPLOYMENT_SERVICES_SERVER";
        case FACILITY_DEPLOYMENT_SERVICES_IMAGING: return u8"FACILITY_DEPLOYMENT_SERVICES_IMAGING";
        case FACILITY_DEPLOYMENT_SERVICES_MANAGEMENT: return u8"FACILITY_DEPLOYMENT_SERVICES_MANAGEMENT";
        case FACILITY_DEPLOYMENT_SERVICES_UTIL: return u8"FACILITY_DEPLOYMENT_SERVICES_UTIL";
        case FACILITY_DEPLOYMENT_SERVICES_BINLSVC: return u8"FACILITY_DEPLOYMENT_SERVICES_BINLSVC";
        case FACILITY_DEPLOYMENT_SERVICES_PXE: return u8"FACILITY_DEPLOYMENT_SERVICES_PXE";
        case FACILITY_DEPLOYMENT_SERVICES_TFTP: return u8"FACILITY_DEPLOYMENT_SERVICES_TFTP";
        case FACILITY_DEPLOYMENT_SERVICES_TRANSPORT_MANAGEMENT: return u8"FACILITY_DEPLOYMENT_SERVICES_TRANSPORT_MANAGEMENT";
        case FACILITY_DEPLOYMENT_SERVICES_DRIVER_PROVISIONING: return u8"FACILITY_DEPLOYMENT_SERVICES_DRIVER_PROVISIONING";
        case FACILITY_DEPLOYMENT_SERVICES_MULTICAST_SERVER: return u8"FACILITY_DEPLOYMENT_SERVICES_MULTICAST_SERVER";
        case FACILITY_DEPLOYMENT_SERVICES_MULTICAST_CLIENT: return u8"FACILITY_DEPLOYMENT_SERVICES_MULTICAST_CLIENT";
        case FACILITY_DEPLOYMENT_SERVICES_CONTENT_PROVIDER: return u8"FACILITY_DEPLOYMENT_SERVICES_CONTENT_PROVIDER";
        case FACILITY_HSP_SERVICES: return u8"FACILITY_HSP_SERVICES";
        case FACILITY_HSP_SOFTWARE: return u8"FACILITY_HSP_SOFTWARE";
        case FACILITY_LINGUISTIC_SERVICES: return u8"FACILITY_LINGUISTIC_SERVICES";
        case FACILITY_AUDIOSTREAMING: return u8"FACILITY_AUDIOSTREAMING";
        case FACILITY_TTD: return u8"FACILITY_TTD";
        case FACILITY_ACCELERATOR: return u8"FACILITY_ACCELERATOR";
        case FACILITY_WMAAECMA: return u8"FACILITY_WMAAECMA";
        case FACILITY_DIRECTMUSIC: return u8"FACILITY_DIRECTMUSIC";
        case FACILITY_DIRECT3D10: return u8"FACILITY_DIRECT3D10";
        case FACILITY_DXGI: return u8"FACILITY_DXGI";
        case FACILITY_DXGI_DDI: return u8"FACILITY_DXGI_DDI";
        case FACILITY_DIRECT3D11: return u8"FACILITY_DIRECT3D11";
        case FACILITY_DIRECT3D11_DEBUG: return u8"FACILITY_DIRECT3D11_DEBUG";
        case FACILITY_DIRECT3D12: return u8"FACILITY_DIRECT3D12";
        case FACILITY_DIRECT3D12_DEBUG: return u8"FACILITY_DIRECT3D12_DEBUG";
        case FACILITY_DXCORE: return u8"FACILITY_DXCORE";
        case FACILITY_PRESENTATION: return u8"FACILITY_PRESENTATION";
        case FACILITY_LEAP: return u8"FACILITY_LEAP";
        case FACILITY_AUDCLNT: return u8"FACILITY_AUDCLNT";
        case FACILITY_WINCODEC_DWRITE_DWM: return u8"FACILITY_WINCODEC_DWRITE_DWM";
        case FACILITY_WINML: return u8"FACILITY_WINML";
        case FACILITY_DIRECT2D: return u8"FACILITY_DIRECT2D";
        case FACILITY_DEFRAG: return u8"FACILITY_DEFRAG";
        case FACILITY_USERMODE_SDBUS: return u8"FACILITY_USERMODE_SDBUS";
        case FACILITY_JSCRIPT: return u8"FACILITY_JSCRIPT";
        case FACILITY_PIDGENX: return u8"FACILITY_PIDGENX";
        case FACILITY_EAS: return u8"FACILITY_EAS";
        case FACILITY_WEB: return u8"FACILITY_WEB";
        case FACILITY_WEB_SOCKET: return u8"FACILITY_WEB_SOCKET";
        case FACILITY_MOBILE: return u8"FACILITY_MOBILE";
        case FACILITY_SQLITE: return u8"FACILITY_SQLITE";
        case FACILITY_SERVICE_FABRIC: return u8"FACILITY_SERVICE_FABRIC";
        case FACILITY_UTC: return u8"FACILITY_UTC";
        case FACILITY_WEP: return u8"FACILITY_WEP";
        case FACILITY_SYNCENGINE: return u8"FACILITY_SYNCENGINE";
        case FACILITY_XBOX: return u8"FACILITY_XBOX";
        case FACILITY_GAME: return u8"FACILITY_GAME";
        case FACILITY_PIX: return u8"FACILITY_PIX";
        default: return u8"Unknown Facility";
    }
}

C8ConstExprString StringifyHResultFacility(const long hResult) noexcept
{
    return StringifyFacility(HRESULT_FACILITY(hResult));
}

C8ConstExprString StringifyHResult(const long hResult) noexcept
{
    switch(hResult)
    {
        case S_OK: return u8"S_OK";
        case S_FALSE: return u8"S_FALSE";
        case E_NOT_SET: return u8"E_NOT_SET";
        case E_NOT_VALID_STATE: return u8"E_NOT_VALID_STATE";
        case E_NOT_SUFFICIENT_BUFFER: return u8"E_NOT_SUFFICIENT_BUFFER";
        case E_TIME_SENSITIVE_THREAD: return u8"E_TIME_SENSITIVE_THREAD";
        case E_NO_TASK_QUEUE: return u8"E_NO_TASK_QUEUE";
        case E_UNEXPECTED: return u8"E_UNEXPECTED";
        case E_NOTIMPL: return u8"E_NOTIMPL";
        case E_OUTOFMEMORY: return u8"E_OUTOFMEMORY";
        case E_INVALIDARG: return u8"E_INVALIDARG";
        case E_NOINTERFACE: return u8"E_NOINTERFACE";
        case E_POINTER: return u8"E_POINTER";
        case E_HANDLE: return u8"E_HANDLE";
        case E_ABORT: return u8"E_ABORT";
        case E_FAIL: return u8"E_FAIL";
        case E_ACCESSDENIED: return u8"E_ACCESSDENIED";
        case E_PENDING: return u8"E_PENDING";
        case E_BOUNDS: return u8"E_BOUNDS";
        case E_CHANGED_STATE: return u8"E_CHANGED_STATE";
        case E_ILLEGAL_STATE_CHANGE: return u8"E_ILLEGAL_STATE_CHANGE";
        case E_ILLEGAL_METHOD_CALL: return u8"E_ILLEGAL_METHOD_CALL";
        case RO_E_METADATA_NAME_NOT_FOUND: return u8"RO_E_METADATA_NAME_NOT_FOUND";
        case RO_E_METADATA_NAME_IS_NAMESPACE: return u8"RO_E_METADATA_NAME_IS_NAMESPACE";
        case RO_E_METADATA_INVALID_TYPE_FORMAT: return u8"RO_E_METADATA_INVALID_TYPE_FORMAT";
        case RO_E_INVALID_METADATA_FILE: return u8"RO_E_INVALID_METADATA_FILE";
        case RO_E_CLOSED: return u8"RO_E_CLOSED";
        case RO_E_EXCLUSIVE_WRITE: return u8"RO_E_EXCLUSIVE_WRITE";
        case RO_E_CHANGE_NOTIFICATION_IN_PROGRESS: return u8"RO_E_CHANGE_NOTIFICATION_IN_PROGRESS";
        case RO_E_ERROR_STRING_NOT_FOUND: return u8"RO_E_ERROR_STRING_NOT_FOUND";
        case E_STRING_NOT_NULL_TERMINATED: return u8"E_STRING_NOT_NULL_TERMINATED";
        case E_ILLEGAL_DELEGATE_ASSIGNMENT: return u8"E_ILLEGAL_DELEGATE_ASSIGNMENT";
        case E_ASYNC_OPERATION_NOT_STARTED: return u8"E_ASYNC_OPERATION_NOT_STARTED";
        case E_APPLICATION_EXITING: return u8"E_APPLICATION_EXITING";
        case E_APPLICATION_VIEW_EXITING: return u8"E_APPLICATION_VIEW_EXITING";
        case RO_E_MUST_BE_AGILE: return u8"RO_E_MUST_BE_AGILE";
        case RO_E_UNSUPPORTED_FROM_MTA: return u8"RO_E_UNSUPPORTED_FROM_MTA";
        case RO_E_COMMITTED: return u8"RO_E_COMMITTED";
        case RO_E_BLOCKED_CROSS_ASTA_CALL: return u8"RO_E_BLOCKED_CROSS_ASTA_CALL";
        case RO_E_CANNOT_ACTIVATE_FULL_TRUST_SERVER: return u8"RO_E_CANNOT_ACTIVATE_FULL_TRUST_SERVER";
        case RO_E_CANNOT_ACTIVATE_UNIVERSAL_APPLICATION_SERVER: return u8"RO_E_CANNOT_ACTIVATE_UNIVERSAL_APPLICATION_SERVER";
        case CO_E_INIT_TLS: return u8"CO_E_INIT_TLS";
        case CO_E_INIT_SHARED_ALLOCATOR: return u8"CO_E_INIT_SHARED_ALLOCATOR";
        case CO_E_INIT_MEMORY_ALLOCATOR: return u8"CO_E_INIT_MEMORY_ALLOCATOR";
        case CO_E_INIT_CLASS_CACHE: return u8"CO_E_INIT_CLASS_CACHE";
        case CO_E_INIT_RPC_CHANNEL: return u8"CO_E_INIT_RPC_CHANNEL";
        case CO_E_INIT_TLS_SET_CHANNEL_CONTROL: return u8"CO_E_INIT_TLS_SET_CHANNEL_CONTROL";
        case CO_E_INIT_TLS_CHANNEL_CONTROL: return u8"CO_E_INIT_TLS_CHANNEL_CONTROL";
        case CO_E_INIT_UNACCEPTED_USER_ALLOCATOR: return u8"CO_E_INIT_UNACCEPTED_USER_ALLOCATOR";
        case CO_E_INIT_SCM_MUTEX_EXISTS: return u8"CO_E_INIT_SCM_MUTEX_EXISTS";
        case CO_E_INIT_SCM_FILE_MAPPING_EXISTS: return u8"CO_E_INIT_SCM_FILE_MAPPING_EXISTS";
        case CO_E_INIT_SCM_MAP_VIEW_OF_FILE: return u8"CO_E_INIT_SCM_MAP_VIEW_OF_FILE";
        case CO_E_INIT_SCM_EXEC_FAILURE: return u8"CO_E_INIT_SCM_EXEC_FAILURE";
        case CO_E_INIT_ONLY_SINGLE_THREADED: return u8"CO_E_INIT_ONLY_SINGLE_THREADED";
        case CO_E_CANT_REMOTE: return u8"CO_E_CANT_REMOTE";
        case CO_E_BAD_SERVER_NAME: return u8"CO_E_BAD_SERVER_NAME";

        case DXGI_STATUS_OCCLUDED: return u8"DXGI_STATUS_OCCLUDED";
        case DXGI_STATUS_CLIPPED: return u8"DXGI_STATUS_CLIPPED";
        case DXGI_STATUS_NO_REDIRECTION: return u8"DXGI_STATUS_NO_REDIRECTION";
        case DXGI_STATUS_NO_DESKTOP_ACCESS: return u8"DXGI_STATUS_NO_DESKTOP_ACCESS";
        case DXGI_STATUS_GRAPHICS_VIDPN_SOURCE_IN_USE: return u8"DXGI_STATUS_GRAPHICS_VIDPN_SOURCE_IN_USE";
        case DXGI_STATUS_MODE_CHANGED: return u8"DXGI_STATUS_MODE_CHANGED";
        case DXGI_STATUS_MODE_CHANGE_IN_PROGRESS: return u8"DXGI_STATUS_MODE_CHANGE_IN_PROGRESS";
        case DXGI_ERROR_INVALID_CALL: return u8"DXGI_ERROR_INVALID_CALL";
        case DXGI_ERROR_NOT_FOUND: return u8"DXGI_ERROR_NOT_FOUND";
        case DXGI_ERROR_MORE_DATA: return u8"DXGI_ERROR_MORE_DATA";
        case DXGI_ERROR_UNSUPPORTED: return u8"DXGI_ERROR_UNSUPPORTED";
        case DXGI_ERROR_DEVICE_REMOVED: return u8"DXGI_ERROR_DEVICE_REMOVED";
        case DXGI_ERROR_DEVICE_HUNG: return u8"DXGI_ERROR_DEVICE_HUNG";
        case DXGI_ERROR_DEVICE_RESET: return u8"DXGI_ERROR_DEVICE_RESET";
        case DXGI_ERROR_WAS_STILL_DRAWING: return u8"DXGI_ERROR_WAS_STILL_DRAWING";
        case DXGI_ERROR_FRAME_STATISTICS_DISJOINT: return u8"DXGI_ERROR_FRAME_STATISTICS_DISJOINT";
        case DXGI_ERROR_GRAPHICS_VIDPN_SOURCE_IN_USE: return u8"DXGI_ERROR_GRAPHICS_VIDPN_SOURCE_IN_USE";
        case DXGI_ERROR_DRIVER_INTERNAL_ERROR: return u8"DXGI_ERROR_DRIVER_INTERNAL_ERROR";
        case DXGI_ERROR_NONEXCLUSIVE: return u8"DXGI_ERROR_NONEXCLUSIVE";
        case DXGI_ERROR_NOT_CURRENTLY_AVAILABLE: return u8"DXGI_ERROR_NOT_CURRENTLY_AVAILABLE";
        case DXGI_ERROR_REMOTE_CLIENT_DISCONNECTED: return u8"DXGI_ERROR_REMOTE_CLIENT_DISCONNECTED";
        case DXGI_ERROR_REMOTE_OUTOFMEMORY: return u8"DXGI_ERROR_REMOTE_OUTOFMEMORY";
        case DXGI_ERROR_ACCESS_LOST: return u8"DXGI_ERROR_ACCESS_LOST";
        case DXGI_ERROR_WAIT_TIMEOUT: return u8"DXGI_ERROR_WAIT_TIMEOUT";
        case DXGI_ERROR_SESSION_DISCONNECTED: return u8"DXGI_ERROR_SESSION_DISCONNECTED";
        case DXGI_ERROR_RESTRICT_TO_OUTPUT_STALE: return u8"DXGI_ERROR_RESTRICT_TO_OUTPUT_STALE";
        case DXGI_ERROR_CANNOT_PROTECT_CONTENT: return u8"DXGI_ERROR_CANNOT_PROTECT_CONTENT";
        case DXGI_ERROR_ACCESS_DENIED: return u8"DXGI_ERROR_ACCESS_DENIED";
        case DXGI_ERROR_NAME_ALREADY_EXISTS: return u8"DXGI_ERROR_NAME_ALREADY_EXISTS";
        case DXGI_ERROR_SDK_COMPONENT_MISSING: return u8"DXGI_ERROR_SDK_COMPONENT_MISSING";
        case DXGI_ERROR_NOT_CURRENT: return u8"DXGI_ERROR_NOT_CURRENT";
        case DXGI_ERROR_HW_PROTECTION_OUTOFMEMORY: return u8"DXGI_ERROR_HW_PROTECTION_OUTOFMEMORY";
        case DXGI_ERROR_DYNAMIC_CODE_POLICY_VIOLATION: return u8"DXGI_ERROR_DYNAMIC_CODE_POLICY_VIOLATION";
        case DXGI_ERROR_NON_COMPOSITED_UI: return u8"DXGI_ERROR_NON_COMPOSITED_UI";
        case DXCORE_ERROR_EVENT_NOT_UNREGISTERED: return u8"DXCORE_ERROR_EVENT_NOT_UNREGISTERED";
        case PRESENTATION_ERROR_LOST: return u8"PRESENTATION_ERROR_LOST";
        case DXGI_STATUS_UNOCCLUDED: return u8"DXGI_STATUS_UNOCCLUDED";
        case DXGI_STATUS_DDA_WAS_STILL_DRAWING: return u8"DXGI_STATUS_DDA_WAS_STILL_DRAWING";
        case DXGI_ERROR_MODE_CHANGE_IN_PROGRESS: return u8"DXGI_ERROR_MODE_CHANGE_IN_PROGRESS";
        case DXGI_STATUS_PRESENT_REQUIRED: return u8"DXGI_STATUS_PRESENT_REQUIRED";
        case DXGI_ERROR_CACHE_CORRUPT: return u8"DXGI_ERROR_CACHE_CORRUPT";
        case DXGI_ERROR_CACHE_FULL: return u8"DXGI_ERROR_CACHE_FULL";
        case DXGI_ERROR_CACHE_HASH_COLLISION: return u8"DXGI_ERROR_CACHE_HASH_COLLISION";
        case DXGI_ERROR_ALREADY_EXISTS: return u8"DXGI_ERROR_ALREADY_EXISTS";
        case DXGI_ERROR_MPO_UNPINNED: return u8"DXGI_ERROR_MPO_UNPINNED";
        case DXGI_DDI_ERR_WASSTILLDRAWING: return u8"DXGI_DDI_ERR_WASSTILLDRAWING";
        case DXGI_DDI_ERR_UNSUPPORTED: return u8"DXGI_DDI_ERR_UNSUPPORTED";
        case DXGI_DDI_ERR_NONEXCLUSIVE: return u8"DXGI_DDI_ERR_NONEXCLUSIVE";
        case D3D10_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS: return u8"D3D10_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS";
        case D3D10_ERROR_FILE_NOT_FOUND: return u8"D3D10_ERROR_FILE_NOT_FOUND";
        case D3D11_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS: return u8"D3D11_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS";
        case D3D11_ERROR_FILE_NOT_FOUND: return u8"D3D11_ERROR_FILE_NOT_FOUND";
        case D3D11_ERROR_TOO_MANY_UNIQUE_VIEW_OBJECTS: return u8"D3D11_ERROR_TOO_MANY_UNIQUE_VIEW_OBJECTS";
        case D3D11_ERROR_DEFERRED_CONTEXT_MAP_WITHOUT_INITIAL_DISCARD: return u8"D3D11_ERROR_DEFERRED_CONTEXT_MAP_WITHOUT_INITIAL_DISCARD";
        case D3D12_ERROR_ADAPTER_NOT_FOUND: return u8"D3D12_ERROR_ADAPTER_NOT_FOUND";
        case D3D12_ERROR_DRIVER_VERSION_MISMATCH: return u8"D3D12_ERROR_DRIVER_VERSION_MISMATCH";
        case D3D12_ERROR_INVALID_REDIST: return u8"D3D12_ERROR_INVALID_REDIST";
        case D2DERR_WRONG_STATE: return u8"D2DERR_WRONG_STATE";
        case D2DERR_NOT_INITIALIZED: return u8"D2DERR_NOT_INITIALIZED";
        case D2DERR_UNSUPPORTED_OPERATION: return u8"D2DERR_UNSUPPORTED_OPERATION";
        case D2DERR_SCANNER_FAILED: return u8"D2DERR_SCANNER_FAILED";
        case D2DERR_SCREEN_ACCESS_DENIED: return u8"D2DERR_SCREEN_ACCESS_DENIED";
        case D2DERR_DISPLAY_STATE_INVALID: return u8"D2DERR_DISPLAY_STATE_INVALID";
        case D2DERR_ZERO_VECTOR: return u8"D2DERR_ZERO_VECTOR";
        case D2DERR_INTERNAL_ERROR: return u8"D2DERR_INTERNAL_ERROR";
        case D2DERR_DISPLAY_FORMAT_NOT_SUPPORTED: return u8"D2DERR_DISPLAY_FORMAT_NOT_SUPPORTED";
        case D2DERR_INVALID_CALL: return u8"D2DERR_INVALID_CALL";
        case D2DERR_NO_HARDWARE_DEVICE: return u8"D2DERR_NO_HARDWARE_DEVICE";
        case D2DERR_RECREATE_TARGET: return u8"D2DERR_RECREATE_TARGET";
        case D2DERR_TOO_MANY_SHADER_ELEMENTS: return u8"D2DERR_TOO_MANY_SHADER_ELEMENTS";
        case D2DERR_SHADER_COMPILE_FAILED: return u8"D2DERR_SHADER_COMPILE_FAILED";
        case D2DERR_MAX_TEXTURE_SIZE_EXCEEDED: return u8"D2DERR_MAX_TEXTURE_SIZE_EXCEEDED";
        case D2DERR_UNSUPPORTED_VERSION: return u8"D2DERR_UNSUPPORTED_VERSION";
        case D2DERR_BAD_NUMBER: return u8"D2DERR_BAD_NUMBER";
        case D2DERR_WRONG_FACTORY: return u8"D2DERR_WRONG_FACTORY";
        case D2DERR_LAYER_ALREADY_IN_USE: return u8"D2DERR_LAYER_ALREADY_IN_USE";
        case D2DERR_POP_CALL_DID_NOT_MATCH_PUSH: return u8"D2DERR_POP_CALL_DID_NOT_MATCH_PUSH";
        case D2DERR_WRONG_RESOURCE_DOMAIN: return u8"D2DERR_WRONG_RESOURCE_DOMAIN";
        case D2DERR_PUSH_POP_UNBALANCED: return u8"D2DERR_PUSH_POP_UNBALANCED";
        case D2DERR_RENDER_TARGET_HAS_LAYER_OR_CLIPRECT: return u8"D2DERR_RENDER_TARGET_HAS_LAYER_OR_CLIPRECT";
        case D2DERR_INCOMPATIBLE_BRUSH_TYPES: return u8"D2DERR_INCOMPATIBLE_BRUSH_TYPES";
        case D2DERR_WIN32_ERROR: return u8"D2DERR_WIN32_ERROR";
        case D2DERR_TARGET_NOT_GDI_COMPATIBLE: return u8"D2DERR_TARGET_NOT_GDI_COMPATIBLE";
        case D2DERR_TEXT_EFFECT_IS_WRONG_TYPE: return u8"D2DERR_TEXT_EFFECT_IS_WRONG_TYPE";
        case D2DERR_TEXT_RENDERER_NOT_RELEASED: return u8"D2DERR_TEXT_RENDERER_NOT_RELEASED";
        case D2DERR_EXCEEDS_MAX_BITMAP_SIZE: return u8"D2DERR_EXCEEDS_MAX_BITMAP_SIZE";
        case D2DERR_INVALID_GRAPH_CONFIGURATION: return u8"D2DERR_INVALID_GRAPH_CONFIGURATION";
        case D2DERR_INVALID_INTERNAL_GRAPH_CONFIGURATION: return u8"D2DERR_INVALID_INTERNAL_GRAPH_CONFIGURATION";
        case D2DERR_CYCLIC_GRAPH: return u8"D2DERR_CYCLIC_GRAPH";
        case D2DERR_BITMAP_CANNOT_DRAW: return u8"D2DERR_BITMAP_CANNOT_DRAW";
        case D2DERR_OUTSTANDING_BITMAP_REFERENCES: return u8"D2DERR_OUTSTANDING_BITMAP_REFERENCES";
        case D2DERR_ORIGINAL_TARGET_NOT_BOUND: return u8"D2DERR_ORIGINAL_TARGET_NOT_BOUND";
        case D2DERR_INVALID_TARGET: return u8"D2DERR_INVALID_TARGET";
        case D2DERR_BITMAP_BOUND_AS_TARGET: return u8"D2DERR_BITMAP_BOUND_AS_TARGET";
        case D2DERR_INSUFFICIENT_DEVICE_CAPABILITIES: return u8"D2DERR_INSUFFICIENT_DEVICE_CAPABILITIES";
        case D2DERR_INTERMEDIATE_TOO_LARGE: return u8"D2DERR_INTERMEDIATE_TOO_LARGE";
        case D2DERR_EFFECT_IS_NOT_REGISTERED: return u8"D2DERR_EFFECT_IS_NOT_REGISTERED";
        case D2DERR_INVALID_PROPERTY: return u8"D2DERR_INVALID_PROPERTY";
        case D2DERR_NO_SUBPROPERTIES: return u8"D2DERR_NO_SUBPROPERTIES";
        case D2DERR_PRINT_JOB_CLOSED: return u8"D2DERR_PRINT_JOB_CLOSED";
        case D2DERR_PRINT_FORMAT_NOT_SUPPORTED: return u8"D2DERR_PRINT_FORMAT_NOT_SUPPORTED";
        case D2DERR_TOO_MANY_TRANSFORM_INPUTS: return u8"D2DERR_TOO_MANY_TRANSFORM_INPUTS";
        case D2DERR_INVALID_GLYPH_IMAGE: return u8"D2DERR_INVALID_GLYPH_IMAGE";
        case DWRITE_E_FILEFORMAT: return u8"DWRITE_E_FILEFORMAT";
        case DWRITE_E_UNEXPECTED: return u8"DWRITE_E_UNEXPECTED";
        case DWRITE_E_NOFONT: return u8"DWRITE_E_NOFONT";
        case DWRITE_E_FILENOTFOUND: return u8"DWRITE_E_FILENOTFOUND";
        case DWRITE_E_FILEACCESS: return u8"DWRITE_E_FILEACCESS";
        case DWRITE_E_FONTCOLLECTIONOBSOLETE: return u8"DWRITE_E_FONTCOLLECTIONOBSOLETE";
        case DWRITE_E_ALREADYREGISTERED: return u8"DWRITE_E_ALREADYREGISTERED";
        case DWRITE_E_CACHEFORMAT: return u8"DWRITE_E_CACHEFORMAT";
        case DWRITE_E_CACHEVERSION: return u8"DWRITE_E_CACHEVERSION";
        case DWRITE_E_UNSUPPORTEDOPERATION: return u8"DWRITE_E_UNSUPPORTEDOPERATION";
        case DWRITE_E_TEXTRENDERERINCOMPATIBLE: return u8"DWRITE_E_TEXTRENDERERINCOMPATIBLE";
        case DWRITE_E_FLOWDIRECTIONCONFLICTS: return u8"DWRITE_E_FLOWDIRECTIONCONFLICTS";
        case DWRITE_E_NOCOLOR: return u8"DWRITE_E_NOCOLOR";
        case DWRITE_E_REMOTEFONT: return u8"DWRITE_E_REMOTEFONT";
        case DWRITE_E_DOWNLOADCANCELLED: return u8"DWRITE_E_DOWNLOADCANCELLED";
        case DWRITE_E_DOWNLOADFAILED: return u8"DWRITE_E_DOWNLOADFAILED";
        case DWRITE_E_TOOMANYDOWNLOADS: return u8"DWRITE_E_TOOMANYDOWNLOADS";

        case D3DDDIERR_OUTOFVIDEOMEMORY: return u8"D3DDDIERR_OUTOFVIDEOMEMORY";
        case D3DDDIERR_WASSTILLDRAWING: return u8"D3DDDIERR_WASSTILLDRAWING";
        case D3DDDIERR_NOTAVAILABLE: return u8"D3DDDIERR_NOTAVAILABLE";
        case D3DDDIERR_INVALIDCALL: return u8"D3DDDIERR_INVALIDCALL";
        case D3DDDIERR_DEVICEREMOVED: return u8"D3DDDIERR_DEVICEREMOVED";
        case D3DDDIERR_PRIVILEGEDINSTRUCTION: return u8"D3DDDIERR_PRIVILEGEDINSTRUCTION";
        case D3DDDIERR_INVALIDINSTRUCTION: return u8"D3DDDIERR_INVALIDINSTRUCTION";
        case D3DDDIERR_INVALIDHANDLE: return u8"D3DDDIERR_INVALIDHANDLE";
        case D3DDDIERR_CANTEVICTPINNEDALLOCATION: return u8"D3DDDIERR_CANTEVICTPINNEDALLOCATION";
        case D3DDDIERR_CANTRENDERLOCKEDALLOCATION: return u8"D3DDDIERR_CANTRENDERLOCKEDALLOCATION";
        case D3DDDIERR_INVALIDUSERBUFFER: return u8"D3DDDIERR_INVALIDUSERBUFFER";
        case D3DDDIERR_INCOMPATIBLEPRIVATEFORMAT: return u8"D3DDDIERR_INCOMPATIBLEPRIVATEFORMAT";
        case D3DDDIERR_UNSUPPORTEDOVERLAY: return u8"D3DDDIERR_UNSUPPORTEDOVERLAY";
        case D3DDDIERR_UNSUPPORTEDOVERLAYFORMAT: return u8"D3DDDIERR_UNSUPPORTEDOVERLAYFORMAT";
        case D3DDDIERR_UNSUPPORTEDCRYPTO: return u8"D3DDDIERR_UNSUPPORTEDCRYPTO";
        case D3DDDIERR_APPLICATIONERROR: return u8"D3DDDIERR_APPLICATIONERROR";
        case D3DDDIERR_OUTOFHWPROTECTEDMEMORY: return u8"D3DDDIERR_OUTOFHWPROTECTEDMEMORY";

        default: return u8"Unknown HRESULT";
    }
}

}

